In [1]:
import numpy as np

In [28]:
num_food = 10
num_users = 5

np.random.seed(0)
ratings = np.random.randint(11, size = (num_food, num_users))

did_rate = (ratings != 0) * 1

macks_ratings = np.zeros((num_food, 1))
macks_ratings[0] = 2
macks_ratings[4] = 10

ratings = np.append(macks_ratings, ratings, axis=1)
print(did_rate)
did_rate = np.append((macks_ratings != 0) * 1, did_rate, axis=1)
print(did_rate)

[[1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [0 1 1 1 1]
 [1 1 1 1 0]
 [1 1 1 0 1]
 [1 1 1 1 1]]
[[1 1 0 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [1 1 1 1 1 1]
 [0 1 1 0 1 1]
 [0 0 1 1 1 1]
 [0 1 1 1 1 0]
 [0 1 1 1 0 1]
 [0 1 1 1 1 1]]


In [56]:
def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = np.zeros(shape = (num_movies, 1))
    ratings_norm = np.zeros(shape = ratings.shape)
    
    for i in range(num_movies): 
        # Get all the indexes where there is a 1
        idx = np.where(did_rate[i] == 1)[0]
        
        #  Calculate mean rating of ith movie only from user's that gave a rating
        ratings_mean[i] = np.mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
    
    return ratings_norm, ratings_mean

In [60]:
ratings_norm, ratings_mean = normalize_ratings(ratings, did_rate)